apiVersion: v2
name: synapse-stack
description: Umbrella chart that installs the Synapse dataplane together with the Synapse operator
# Release synapse-stack v0.1.2
type: application
version: 0.1.2
appVersion: "0.3.1"
home: https://arxignis.com
icon: https://raw.githubusercontent.com/arxignis/helm-charts/main/images/logo.png
sources:
  - https://github.com/gen0sec/synapse
  - https://github.com/arxignis/synapse-operator
keywords:
  - synapse
  - operator
  - kubernetes
  - security
  - proxy
  - firewall
dependencies:
  - name: synapse
    version: 0.1.2
    repository: "file://../synapse"
    condition: synapse.enabled
maintainers:
  - name: Arxignis
    email: support@arxignis.com
