apiVersion: v2
name: moat-operator
description: Helm chart for the Moat Kubernetes operator
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://arxignis.com
icon: https://raw.githubusercontent.com/arxignis/helm-charts/main/images/logo.png
sources:
  - https://github.com/arxignis/moat-operator
keywords:
  - moat
  - operator
  - kubernetes
  - security
maintainers:
  - name: Arxignis
    email: support@arxignis.com

