apiVersion: v2
name: moat-stack
description: Umbrella chart that installs the Moat dataplane together with the Moat operator
type: application
version: 0.1.1
appVersion: "0.1.0"
dependencies:
  - name: moat
    version: 0.1.0
    repository: "file://.."
maintainers:
  - name: Arxignis
    email: support@arxignis.com
