{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "synapse-operator" .Values.operator.serviceAccount.name }}
  namespace: {{ .Values.global.namespaces.operator }}
  labels:
    app.kubernetes.io/name: synapse-operator
{{- end }}
