{{- if and .Values.operator.enabled .Values.operator.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.operator }}
  labels:
    app.kubernetes.io/name: moat-operator
{{- end }}
