apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.synapse.config | nindent 4 }}
  upstreams.yaml: |
{{ .Values.synapse.upstreams | nindent 4 }}