{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-operator
  namespace: {{ .Values.global.namespaces.operator }}
  labels:
    app.kubernetes.io/name: synapse-operator
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ default "synapse-operator" .Values.operator.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            {{- if .Values.operator.leaderElect }}
            - --leader-elect
            {{- end }}
            {{- if .Values.operator.labelSelector }}
            - --label-selector={{ .Values.operator.labelSelector }}
            {{- end }}
            {{- if .Values.operator.configHashAnnotation }}
            - --config-hash-annotation={{ .Values.operator.configHashAnnotation }}
            {{- end }}
            {{- if .Values.operator.ignoreConfigMapKeys }}
            - --ignore-configmap-keys={{ .Values.operator.ignoreConfigMapKeys }}
            {{- end }}
            {{- if .Values.operator.ignoreSecretKeys }}
            - --ignore-secret-keys={{ .Values.operator.ignoreSecretKeys }}
            {{- end }}
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
{{- end }}
